# Generated by Django 2.0.2 on 2018-03-08 19:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('myMovsDisplay', '0005_auto_20180302_1843'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaccion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(verbose_name='fecha de cargo')),
                ('descripcion', models.CharField(max_length=150)),
                ('cargo', models.FloatField(default=0.0)),
                ('abono', models.FloatField(default=0.0)),
                ('saldo', models.CharField(max_length=30)),
                ('NumTarjeta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myMovsDisplay.Tarjeta')),
            ],
        ),
    ]
