# Generated by Django 2.0.2 on 2018-03-02 18:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Banco',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombre', models.CharField(max_length=200)),
                ('Activo', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tarjeta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NumTarjeta', models.CharField(max_length=30)),
                ('Banco', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myMovsDisplay.Banco')),
            ],
        ),
        migrations.CreateModel(
            name='TipoTarjeta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Tipo', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Transacciones',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(verbose_name='fecha de cargo')),
                ('descripcion', models.CharField(max_length=200)),
                ('cargo', models.IntegerField(default=0)),
                ('abono', models.IntegerField(default=0)),
                ('saldo', models.IntegerField(default=0)),
                ('NumTarjeta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myMovsDisplay.Tarjeta')),
            ],
        ),
        migrations.AddField(
            model_name='tarjeta',
            name='TipoTarjeta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myMovsDisplay.TipoTarjeta'),
        ),
    ]
