# Generated by Django 2.0.2 on 2018-03-03 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myMovsDisplay', '0002_auto_20180302_1806'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transacciones',
            name='saldo',
            field=models.CharField(max_length=30),
        ),
    ]
