# Generated by Django 2.0.2 on 2018-03-09 04:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='transaccion',
            unique_together={('fecha', 'descripcion', 'cargo', 'abono')},
        ),
    ]
