# Generated by Django 2.0.2 on 2018-03-23 04:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0002_auto_20180308_2234'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='transaccion',
            unique_together={('fecha', 'descripcion', 'cargo', 'abono', 'saldo')},
        ),
    ]
