# Generated by Django 2.0.2 on 2018-03-03 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myMovsDisplay', '0003_auto_20180302_1812'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transacciones',
            name='abono',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='transacciones',
            name='cargo',
            field=models.FloatField(default=0.0),
        ),
    ]
