# Generated by Django 2.0.2 on 2018-03-03 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myMovsDisplay', '0004_auto_20180302_1837'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transacciones',
            name='descripcion',
            field=models.CharField(max_length=150),
        ),
    ]
